// Built-in sound library definitions with high quality sounds
export const SOUND_LIBRARY = [
  {
    name: 'Meow',
    category: 'Animals',
    type: 'synthesized',
    icon: '🐱',
    description: 'Realistic cat meow sound effect',
  },
  {
    name: 'Bark',
    category: 'Animals',
    type: 'synthesized',
    icon: '🐶',
    description: 'Realistic dog bark sound effect',
  },
  {
    name: 'Chirp',
    category: 'Animals',
    type: 'synthesized',
    icon: '🐦',
    description: 'Bird chirp sound effect',
  },
  {
    name: 'Pop',
    category: 'Effects',
    type: 'synthesized',
    icon: '🫧',
    description: 'Crisp bubble pop sound effect',
  },
  {
    name: 'Laser',
    category: 'Effects',
    type: 'synthesized',
    icon: '⚡',
    description: 'Sci-fi laser beam sound effect',
  },
  {
    name: 'Coin',
    category: 'Effects',
    type: 'synthesized',
    icon: '🪙',
    description: 'Arcade 8-bit coin ding sound',
  },
  {
    name: 'Boing',
    category: 'Effects',
    type: 'synthesized',
    icon: '🌀',
    description: 'Cartoon spring boing effect',
  },
  {
    name: 'Bell',
    category: 'Effects',
    type: 'synthesized',
    icon: '🔔',
    description: 'Crystal clear bell chime',
  },
  {
    name: 'Whistle',
    category: 'Effects',
    type: 'synthesized',
    icon: '😙',
    description: 'Referee whistle sound effect',
  },
  {
    name: 'Piano',
    category: 'Music',
    type: 'synthesized',
    icon: '🎹',
    description: 'Acoustic piano key note',
  },
  {
    name: 'Drum Kick',
    category: 'Music',
    type: 'synthesized',
    icon: '🥁',
    description: 'Punchy bass drum kick',
  },
  {
    name: 'Snare',
    category: 'Music',
    type: 'synthesized',
    icon: '🪘',
    description: 'Crisp snare drum hit',
  },
  {
    name: 'Guitar',
    category: 'Music',
    type: 'synthesized',
    icon: '🎸',
    description: 'Plucked acoustic guitar chord',
  },
  {
    name: 'Victory',
    category: 'Music',
    type: 'synthesized',
    icon: '🏆',
    description: 'Triumphant fanfare jingle',
  },
  {
    name: 'Applause',
    category: 'Voice',
    type: 'synthesized',
    icon: '👏',
    description: 'Crowd applause & cheering effect',
  },
];
