// Pico MicroPython Code Builder
// Wraps buildESP32Code() with Pico-specific post-processing.
//
// The MicroPython `machine` module API is nearly identical between ESP32 and
// Raspberry Pi Pico (Pin, PWM, ADC, I2C, SPI, UART, Timer).
// Only ESP32-specific modules (esp, esp32, network, bluetooth GATT stack,
// capacitive touch, Hall sensor) differ and must be removed.

import { buildESP32Code } from './codeBuilder';

// Lines that contain these module names are ESP32-only and invalid on Pico
const ESP32_ONLY_MODULES = [
  /^\s*import esp32\b/,
  /^\s*import esp\b/,
  /^\s*from esp32\s+import/,
  /^\s*from esp\s+import/,
  // esp32.hall_sensor() call
  /esp32\.hall_sensor/,
  // TouchPad — ESP32 capacitive touch, not on Pico
  /TouchPad/,
];

// Lines that reference these and need substitution
const ESP32_SUBSTITUTIONS = [
  // esp32.hall_sensor() → 0  (graceful no-op)
  [/esp32\.hall_sensor\(\)/g, '0'],
];

/**
 * Build clean MicroPython code for the Raspberry Pi Pico.
 * - Runs the same structural builder as ESP32 (imports, setup, while True)
 * - Strips/replaces ESP32-only module calls
 * - Prepends a Pico platform header comment
 *
 * @param {string} rawCode  Raw Blockly-generated Python string
 * @returns {string}        Ready-to-upload MicroPython for Pico
 */
export function buildPicoCode(rawCode) {
  // 1. Run the same structural builder as ESP32
  let code = buildESP32Code(rawCode);

  // 2. Apply substitutions first (replace before stripping)
  for (const [pattern, replacement] of ESP32_SUBSTITUTIONS) {
    code = code.replace(pattern, replacement);
  }

  // 3. Strip lines containing ESP32-only modules
  const lines = code.split('\n');
  const filtered = lines.filter(line => {
    return !ESP32_ONLY_MODULES.some(re => re.test(line));
  });
  code = filtered.join('\n');

  // 4. Prepend Pico platform header
  const header = [
    '# ── Raspberry Pi Pico — MicroPython ───────────────────────────────────',
    '# Generated by TechyGuide TechyBlocks',
    '# Flash MicroPython firmware once: https://micropython.org/download/rp2-pico/',
    '# Then click "Upload Code" in TechyBlocks to push this code via USB.',
    '',
  ].join('\n');

  return header + code;
}
